#!/usr/bin/env python3
"""Regenerate docs/superpowers/README.md: an index of a repo's specs and plans.

    python spec-index.py [DOCS_DIR]      # DOCS_DIR defaults to ./docs/superpowers

Each spec/plan row shows its date, title (linked) and Status. Title is the first
``# `` heading (fallback: file stem); Status comes from a ``**Status:**`` line
(fallback: an em dash); Date from a ``**Date:**`` line, else the filename's
``YYYY-MM-DD-`` prefix. Nothing is written when the content is unchanged, and
nothing at all when neither specs/ nor plans/ exists. Always exits 0.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = (
    "# Specs and plans\n\n"
    "<!-- generated by claude-kit spec-index.py; do not edit by hand -->\n"
)
TITLE_RE = re.compile(r"^# (.+?)\s*$", re.M)
STATUS_RE = re.compile(r"\*\*Status:\*\*\s*([a-z]+)")
DATE_RE = re.compile(r"\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})")
FILE_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-")
MISSING = "—"


def entry(md: Path) -> tuple[str, str, str]:
    """Return (date, title, status) for one spec or plan."""
    text = md.read_text(encoding="utf-8")
    title_match = TITLE_RE.search(text)
    title = title_match.group(1) if title_match else md.stem
    status_match = STATUS_RE.search(text)
    status = status_match.group(1) if status_match else MISSING
    date_match = DATE_RE.search(text) or FILE_DATE_RE.search(md.name)
    date = date_match.group(1) if date_match else MISSING
    return date, title.replace("|", "\\|"), status


def section(label: str, folder: Path, docs_dir: Path) -> str:
    lines = [f"## {label}s", "", f"| Date | {label} | Status |", "|---|---|---|"]
    if folder.is_dir():
        rows = []
        for md in folder.glob("*.md"):
            date, title, status = entry(md)
            rel = md.relative_to(docs_dir).as_posix()
            rows.append((date, md.name, f"| {date} | [{title}]({rel}) | {status} |"))
        rows.sort(key=lambda r: r[1])
        rows.sort(key=lambda r: r[0], reverse=True)
        lines.extend(row for _, _, row in rows)
    return "\n".join(lines) + "\n"


def render(docs_dir: Path) -> str:
    specs = section("Spec", docs_dir / "specs", docs_dir)
    plans = section("Plan", docs_dir / "plans", docs_dir)
    return HEADER + "\n" + specs + "\n" + plans


def write_index(docs_dir: Path) -> Path | None:
    if not (docs_dir / "specs").is_dir() and not (docs_dir / "plans").is_dir():
        return None
    out = docs_dir / "README.md"
    text = render(docs_dir)
    if out.exists() and out.read_text(encoding="utf-8") == text:
        return out
    out.write_text(text, encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    docs_dir = Path(argv[0]) if argv else Path.cwd() / "docs" / "superpowers"
    try:
        write_index(docs_dir)
    except Exception as exc:  # never block a hook
        print(f"[claude-kit] spec-index error: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
