import os
import time

from helpers import PLUGIN, load_module, run_script

SCRIPT = PLUGIN / "scripts" / "spec-index.py"


def mod():
    return load_module(SCRIPT, "spec_index")


def make(docs, kind, name, text):
    folder = docs / kind
    folder.mkdir(parents=True, exist_ok=True)
    (folder / name).write_text(text, encoding="utf-8")


def test_missing_dirs_write_nothing(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    docs.mkdir(parents=True)
    assert mod().write_index(docs) is None
    assert not (docs / "README.md").exists()


def test_empty_dirs_produce_header_only_tables(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    (docs / "specs").mkdir(parents=True)
    (docs / "plans").mkdir()
    out = mod().write_index(docs)
    text = out.read_text(encoding="utf-8")
    assert text.startswith("# Specs and plans\n\n<!-- generated by claude-kit")
    assert "## Specs\n\n| Date | Spec | Status |\n|---|---|---|\n" in text
    assert "## Plans\n\n| Date | Plan | Status |\n|---|---|---|\n" in text


def test_rows_parse_title_status_date_and_sort_newest_first(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    make(
        docs,
        "specs",
        "2026-01-01-old-design.md",
        "# Old thing\n\n- **Status:** implemented\n- **Date:** 2026-01-01\n",
    )
    make(
        docs,
        "specs",
        "2026-03-05-new-design.md",
        "# New | thing\n\n- **Status:** approved\n- **Date:** 2026-03-05\n",
    )
    make(docs, "plans", "2026-02-02-plan.md", "# The plan\n\nno status line\n")
    text = mod().render(docs)
    specs = text.split("## Specs")[1].split("## Plans")[0]
    old = specs.index("Old thing")
    new = specs.index("New \\| thing")
    assert new < old, "newest first"
    assert (
        "| 2026-03-05 | [New \\| thing](specs/2026-03-05-new-design.md) | approved |"
        in text
    )
    assert "| 2026-02-02 | [The plan](plans/2026-02-02-plan.md) | — |" in text


def test_title_falls_back_to_stem_and_date_to_filename(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    make(docs, "specs", "2026-04-04-bare.md", "no heading\n")
    text = mod().render(docs)
    assert "| 2026-04-04 | [2026-04-04-bare](specs/2026-04-04-bare.md) | — |" in text


def test_second_run_does_not_rewrite(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    make(docs, "specs", "2026-01-01-a.md", "# A\n")
    out = mod().write_index(docs)
    first = os.stat(out).st_mtime_ns
    time.sleep(0.05)
    mod().write_index(docs)
    assert os.stat(out).st_mtime_ns == first


def test_cli_defaults_to_cwd_docs_superpowers_and_exits_zero(tmp_path):
    docs = tmp_path / "docs" / "superpowers"
    make(docs, "specs", "2026-01-01-a.md", "# A\n")
    result = run_script(SCRIPT, cwd=tmp_path)
    assert result.returncode == 0, result.stderr
    assert (docs / "README.md").exists()
    assert run_script(SCRIPT, str(tmp_path / "nowhere")).returncode == 0
